DROP DATABASE IF EXISTS dkf;
CREATE DATABASE dkf;
USE dkf;

CREATE TABLE User(
    UserID VARCHAR(6) NOT NULL,
    UserName VARCHAR(20) NOT NULL,
    Password VARCHAR(10) NOT NULL,
    UserEmail VARCHAR(50) NOT NULL ,
    UserContact VARCHAR(12) NOT NULL,
    CONSTRAINT PRIMARY KEY (UserID)
);

CREATE TABLE LogHistory(
    UserID VARCHAR(6) NOT NULL,
    LogIn DATETIME,
    logOut DATETIME,
    CONSTRAINT FOREIGN KEY(UserID) REFERENCES User(UserID)
);



